### ISSUE TITLE
XDebug not working in yiisoftware/yii2-php:7.4-fpm

### ISSUE THREAD

**Issue by thecerber** [yiisoft/yii2-docker#100]
In my opinion here is a similar problem for an earlier version of the image: https://github.com/yiisoft/yii2-docker/issues/58

Here is my service configurations:
```
  app:
    build:
      context: ./docker/app
    container_name: app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      - PHP_ENABLE_XDEBUG=1
    expose:
      - 9000
```

Images builds without any errors, but xdebug not working.
