### ISSUE TITLE
Php-fpm image - xdebug output format problem

### ISSUE THREAD

**Issue by zemkogabor** [yiisoft/yii2-docker#102]
PHP service in `docker-compose.yml`:

```
  php:
    image: yiisoftware/yii2-php:7.4-fpm
    restart: always
    container_name: php
    environment:
      PHP_ENABLE_XDEBUG: 1
      XDEBUG_CONFIG: "default_enable=1"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
```

Xdebug is correctly enabled, but the "pretty" var_dump not working.

<img width="1194" alt="Screenshot 2020-10-10 at 11 25 47" src="https://user-images.githubusercontent.com/39522338/95651551-72876400-0aeb-11eb-8efd-491b3a23e7e3.png">

I try to set `default_enable` in compose file, but for some reason it is **always** off.

<img width="828" alt="Screenshot 2020-10-10 at 11 25 05" src="https://user-images.githubusercontent.com/39522338/95651599-c3975800-0aeb-11eb-8009-ceda164860c4.png">

_(The `html_errors` enabled in php.ini.)_

Anyone any idea?

Thank you
