### ISSUE TITLE
CI fails after the last image change on docker hub

### ISSUE THREAD

**Issue by odai-alali** [yiisoft/yii2-docker#104]
Hi,

I have a ci running on my private gitlab, It is failing now without changing my ci config. It seems that xdebud is missing from the last pushed image

```
error: 'xdebug' does not exist
usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
Possible values for module-name:
bcmath.so curl.so exif.so gd.so iconv.so imagick.so intl.so mbstring.so mongodb.so opcache.so pdo_mysql.so pdo_pgsql.so soap.so zip.so
Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
```

I noticed from the logs that the docker image sha is changed [sha256:8ecbf8e08cf8e30ff63e4f79b998e04014e7631be6ee2e3bbf1df03559266792](https://hub.docker.com/layers/yiisoftware/yii2-php/7.1-apache/images/sha256-8ecbf8e08cf8e30ff63e4f79b998e04014e7631be6ee2e3bbf1df03559266792?context=explore). so I think the cause of the problem is in the last pushed image.

I am using `yiisoftware/yii2-php:7.1-apache`

## Passed CI Log
```
Running with gitlab-runner 13.6.0 (8fa89735)
  on runner on internal server oyUbFdD6
Preparing the "docker" executor
00:18
Using Docker executor with image yiisoftware/yii2-php:7.1-apache ...
Starting service mariadb:latest ...
Pulling docker image mariadb:latest ...
Using docker image sha256:3a348a04a8159339ed3ca053ea925f854252e6a6c3df6fa82c17625d1026f18b for mariadb:latest with digest mariadb@sha256:cdc553f0515a8d41264f0855120874e86761f7c69407b5cfbe49283dc195bea8 ...
Waiting for services to be up and running...
Pulling docker image yiisoftware/yii2-php:7.1-apache ...
Using docker image sha256:54316e05094012f45f0b0968495341a55bfc19aaa6224926109c5670a30bf296 for yiisoftware/yii2-php:7.1-apache with digest yiisoftware/yii2-php@sha256:b31a7a5fa335de73fc113dd3c8625a6e1c33aa0e92476794fe41e3e942f9d93a ...
Preparing environment
00:02
Running on runner-oyubfdd6-project-76-concurrent-0 via b8e10b9b973b...
Getting source from Git repository
00:02
Fetching changes...
Reinitialized existing Git repository in /builds/dis/dis/.git/
Checking out f074541b as 363-12-special-value-lists...
Skipping Git submodules setup
Executing "step_script" stage of the job script
01:49
usermod: no changes
Enabled xdebug
....
```

## Failed CI Log
```
Running with gitlab-runner 13.6.0 (8fa89735)
  on runner on internal server oyUbFdD6
Preparing the "docker" executor
00:18
Using Docker executor with image yiisoftware/yii2-php:7.1-apache ...
Starting service mariadb:latest ...
Pulling docker image mariadb:latest ...
Using docker image sha256:3a348a04a8159339ed3ca053ea925f854252e6a6c3df6fa82c17625d1026f18b for mariadb:latest with digest mariadb@sha256:cdc553f0515a8d41264f0855120874e86761f7c69407b5cfbe49283dc195bea8 ...
Waiting for services to be up and running...
Pulling docker image yiisoftware/yii2-php:7.1-apache ...
Using docker image sha256:ef909b8f5d93b29211b51956996bd5f9905a8f5f2fcb520b7d0dc3f3f87d22b6 for yiisoftware/yii2-php:7.1-apache with digest yiisoftware/yii2-php@sha256:8ecbf8e08cf8e30ff63e4f79b998e04014e7631be6ee2e3bbf1df03559266792 ...
Preparing environment
00:01
Running on runner-oyubfdd6-project-76-concurrent-0 via b8e10b9b973b...
Getting source from Git repository
00:02
Fetching changes...
Reinitialized existing Git repository in /builds/dis/dis/.git/
Checking out f074541b as 363-12-special-value-lists...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
usermod: no changes
error: 'xdebug' does not exist
usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
Possible values for module-name:
bcmath.so curl.so exif.so gd.so iconv.so imagick.so intl.so mbstring.so mongodb.so opcache.so pdo_mysql.so pdo_pgsql.so soap.so zip.so
Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

## .gitlab-ci.yml

```yml
image: yiisoftware/yii2-php:7.1-apache

services:
  - name: mariadb:latest
    alias: db

variables:
  MYSQL_USER: db_user
  MYSQL_PASSWORD: db_password
  MYSQL_DATABASE: test_test
  MYSQL_ROOT_PASSWORD: root_password
  PHP_ENABLE_XDEBUG: 1

stages:
  - backend_test
  - frontend_test

test_backend:
  stage: backend_test
  before_script:
    - ln -s "$(pwd)/web" /app/web
    - apachectl start
  script:
    - cp .env-test .env
    - composer install
    - chmod +x yii
    - ./yii migrate --interactive=0
    - ./backend/vendor/bin/codecept run --coverage-text --coverage-html --no-colors
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    paths:
      - backend/tests/_output/coverage
  tags:
    - shared
  only:
    refs:
      - branches
```
