### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kuhnflyfish** [yiisoft/yii2-docker#121]
I'm getting a 403 forbidden as well as 'AH00112: Warning: DocumentRoot [/app/web] does not exist' and 'AH01630: client denied by server configuration: /app/web' in docker logs.

When in the container, the /app directory is empty.  Below is my docker-compose.yml file where I've made two changes:

```
version: '2.2'
services:

  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
        - PECL_XDEBUG_INSTALL_SUFFIX
        - PECL_MONGODB_INSTALL_SUFFIX
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./app:/app:delegated
      - ./tests:/tests:delegated
      # Framework testing
      - ./_host-volumes/yii2:/yii2:delegated
      # Application testing
      - ./_host-volumes/app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8000:80'
```

I've added the first volume in the list to mount my app dir, and then specified a port mapping.  Any help is appreciated.
