### ISSUE TITLE
PHP hangs using Xdebug

### ISSUE THREAD

**Issue by cccaballero** [yiisoft/yii2-docker#122]
I am using the yii2 advanced template and `yiisoftware/yii2-php:7.4-apache` image. When I setup my docker compose as:

```
services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    environment:
      PHP_ENABLE_XDEBUG: 1
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
```

PHP hangs like forever (no matter if is running from CLI or browser). As I am running from linux, if I do not include the `extra_hosts` it does not hangs, but throws the error: 

```
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9005 (through xdebug.client_host/xdebug.client_port) :-(
```

I am using PhpStorm as IDE and configured the Xdebug port to 9005.
