### ISSUE TITLE
yii command running from vendor/bin doesn't load config

### ISSUE THREAD

**Issue by garrettw** [yiisoft/yii2-docker#140]
I have noticed when using the official yii2 docker image that running the `yii` command in the project root (which refers to `vendor/bin/yii` according to the `PATH` set in the container) always complains about not being able to instantiate the db class. I was able to determine that it is not loading my `config/console.php` file.

In order to get it working, I had to include [the `yii` file from the basic app template](https://github.com/yiisoft/yii2-app-basic/blob/master/yii) in my project root, set it as executable, and restart my terminal -- so then the `yii` command refers to this new file.

Is this a bug? It sure seems like it is. If not, am I doing something wrong? I would prefer not to include the extra executable in my project if possible.

**Comment by schmunk42** [comment]
Can you post the commands you run?
There's no `yii` by default on an image.

```
root@f557761a3c07:/app# echo $PATH
/app:/app/vendor/bin:/root/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@f557761a3c07:/app# which yii
```

**Comment by garrettw** [comment]
Right, but there is in `/app/vendor/bin` which comes in from the docker-compose volume.

**docker-compose.yml:**
```yaml
version: '3'
services:
    php-apache:
        build: ./docker
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:cached
            - .:/app:cached
        networks:
            - default
        links:
            - 'test_mysql'

    test_mysql:
        image: mysql:5.7.24
        container_name: testmysql
        ports:
          - "6603:3306"
        environment:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: "mypassword"
        volumes:
          - ./docker/dbdata:/var/lib/mysql
        networks:
          - default

networks:
  default:
    driver: bridge
    ipam:
       driver: default
       config:
       - subnet: 10.20.22.0/24

volumes:
    dbdata:
        driver: local
```

**docker/Dockerfile:**
```Dockerfile
# PHP Docker image for Yii 2.0 Framework runtime
# ==============================================

FROM yiisoftware/yii2-php:7.3-apache

ENV DEBIAN_FRONTEND=noninteractive

# Install system packages for PHP extensions recommended for Yii 2.0 Framework
# mkdir is for installing java for pdftk
RUN mkdir -p /usr/share/man/man1; \
    apt-get update \
    && apt-get install -y gnupg2 \
    && curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-key update \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        nodejs \
        g++ \
        git \
        curl \
        imagemagick \
        libfreetype6-dev \
        libcurl3-dev \
        libicu-dev \
        libfreetype6-dev \
        libjpeg-dev \
        libjpeg62-turbo-dev \
        libmagickwand-dev \
        libpq-dev \
        libpng-dev \
        libxml2-dev \
        libzip-dev \
        zlib1g-dev \
        default-mysql-client \
        openssh-client \
        nano \
        unzip \
        xmlsec1\
        pdftk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g yarn \
    && yarn install

# Add configuration files
COPY 000-default.conf /etc/apache2/sites-available/
COPY ssl-cert-snakeoil.pem /etc/ssl/certs/
COPY ssl-cert-snakeoil.key /etc/ssl/private/

# Create a symlink for apache (if `/var/www/html` is available)
RUN (rm -rf /var/www/html && mkdir /var/www/html && ln -s /app/web/ /var/www/html) || true

RUN a2enmod ssl
RUN chmod -R 777 /var/log
```
