### ISSUE TITLE
Forbidden with running config for Yii advance

### ISSUE THREAD

**Issue by Chienle** [yiisoft/yii2-docker#28]
Hi guys,

I have config docker-compose.yml for Yii 2 with advanced template bellow:
```
version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/backend:delegated
    ports:
      - "80:80"
  mongo:
    image: 'mongo:3.6'
    ports:
      - '27017:27017'
```
When I executing command and get messages: docker-compose up -d --build
```
Creating network "apkreview_default" with the default driver
Creating apkreview_php_1   ... done
Creating apkreview_mongo_1 ... done
```
When I access to domain local: localhost
Then I got 403 message http://prntscr.com/inogeq

Please support me how to config correct it,
Thank you so much!
