### ISSUE TITLE
Correct way to enable xdebug on official image

### ISSUE THREAD

**Issue by azdanov** [yiisoft/yii2-docker#36]
When using `yiisoftware/yii2-php:7.2-apache` is there a correct way to enable xdebug without manually connecting to the container? Should I do it in the `Dockerfile`?

I've tried adding `PHP_ENABLE_XDEBUG=1` to my `docker-compose.yml`, but it resulted in an error:

```
error: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc

Possible values for module-name:
bcmath.so curl.so exif.so gd.so iconv.so imagick.so intl.so mbstring.so opcache.so pdo_mysql.so pdo_pgsql.so soap.so zip.so

Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
```

Here's my `Dockerfile`:

```
FROM yiisoftware/yii2-php:7.2-apache
RUN a2enmod rewrite
```

And `docker-compose.yml`:
```yaml
version: '3.3'
services:
    app:
        build: .
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        environment:
            - PHP_ENABLE_XDEBUG=1
        ports:
            - 8000:80
        depends_on:
            - db
            - cache
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: yii2testing
            MYSQL_USER: yii2
            MYSQL_PASSWORD: yii2
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
    cache:
          image: redis:latest
          restart: always
          volumes:
            - cache_data:/data
          ports:
            - 6379:6379
volumes:
    db_data:
    cache_data:
```

PS: Should I also be running `a2enmod rewrite` in `Dockerfile`, or am I missing again some command flag to enable it?
