### ISSUE TITLE
enable xDebug from docker-compose.yml

### ISSUE THREAD

**Issue by odai-alali** [yiisoft/yii2-docker#58]
Hi, 
I am new to docker and appreciate a little help
I have the following `docker-compose.yml`
```yml
version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: 1
    ports:
      - '8000:80'
```
when I run `docker-compose up` I get an error
```
 error: 'xdebug' does not exist
```

I am not sure if I understand this well. Shouldn't it work this way? or should I clone the repository and build my own image with xDebug enabled and then use my image?

> UPDATE
I've built a local image with PHP_ENABLE_XDEBUG=1 and then used this image like this
```yml
version: '2'
services:
  php:
    image: local/yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: 1
    ports:
      - '8000:80'
```
xDebug is now working. 

Why xDebug is not installed by default on the images on [Docker Hub](https://hub.docker.com/r/yiisoftware/yii2-php/tags/) as long as it could be disabled by the environment variable `PHP_ENABLE_XDEBUG`

**Comment by odai-alali** [comment]
according to #36, I tried to do the following 
`docker-compose.yml`
```yml
version: '2'
services:
  php:
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: 1
    ports:
      - '8000:80'
```

`Dockerfile`
```
FROM yiisoftware/yii2-php:7.1-apache

# Install xdebug
RUN cd /tmp && \
    git clone git://github.com/xdebug/xdebug.git && \
    cd xdebug && \
    git checkout 52adff7539109db592d07d3f6c325f6ee2a7669f && \
    phpize && \
    ./configure --enable-xdebug && \
    make && \
    make install && \
    rm -rf /tmp/xdebug
```
In the terminal after `docker-compose up`, I am able to see `Enabled xdebug` But xDebug did not work

**Comment by niklaswolf** [comment]
I am running in the same issue.
docker-compose.yml
```
version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      - PHP_ENABLE_XDEBUG=1
    ports:
      - '8000:80'
```
Are we missing something @schmunk42?
