### ISSUE TITLE
Images at DockerHub are built without xdebug support

### ISSUE THREAD

**Issue by whocaresk** [yiisoft/yii2-docker#75]
And there is no way to enable it during build. At this moment docs are misleading and make you think that putting PHP_ENABLE_XDEBUG=1 in .env or docker-compose file will really enable xdebug.

example Dockerfile:
```Dockerfile
FROM yiisoftware/yii2-php:7.3-apache

WORKDIR /app

COPY ./composer* ./

RUN composer install --ignore-platform-reqs && \
    mv vendor/bower-asset vendor/bower

COPY ./docker/config/000-default.conf /etc/apache2/sites-available/000-default.conf

COPY . .
```
```yaml
version: '3.2'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - 1337:80
    volumes:
    # Re-use local composer cache via host-volume
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    # Mount source-code for development
    - ./:/app
    - /app/vendor/
    environment:
    - PHP_ENABLE_XDEBUG=1
```
We can ensure that there is no files was created for xdebug (config, etc) by logging into created container and checking /etc/php/conf.d/xdebug.ini (there is no such file)
